apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: web-frontend
    app: web-frontend
spec:
  selector:
    name: web-frontend
    app: web-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002

